### ISSUE TITLE
asciidoctor 2.0 기반 빌드 오류 (PDF, HTML 등)

### ISSUE THREAD

**Issue by lethee** [progit/progit2-ko#114]
```
# Gemfile 일부

gem 'asciidoctor', '2.0.12'

gem 'asciidoctor-epub3', '1.5.0.alpha.19'
gem 'asciidoctor-pdf', '1.5.4'
gem 'asciidoctor-pdf-cjk', '~> 0.1.3'
gem 'asciidoctor-pdf-cjk-kai_gen_gothic', '~> 0.1.1'
```

현재 위 내용으로 PDF 빌드시 한글이 제대로 출력되지 않는 문제가 있음.

일단 ruby 2.7, linux 기반 환경 에서 한글 html, pdf 빌드가 제대로 되도록 설정해야 한다.

**Comment by lethee** [comment]
asciidoc 1.5 대에서 2.0 대로 업데이트 되면서 CJK 문제 발생하는 듯.

* https://github.com/asciidoctor/asciidoctor-pdf/issues/1765
* https://github.com/asciidoctor/asciidoctor-pdf#create-a-custom-cjk-theme

**Comment by lethee** [comment]
```
$ bundle exec asciidoctor-pdf --trace -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicKR progit.asc
Traceback (most recent call last):
	36: from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
	35: from /usr/local/bin/asciidoctor-pdf:23:in `load'
	34: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/bin/asciidoctor-pdf:27:in `<top (required)>'
	33: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:113:in `invoke!'
	32: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:113:in `each'
	31: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:130:in `block in invoke!'
	30: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:189:in `convert_file'
	29: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:189:in `open'
	28: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:189:in `block in convert_file'
	27: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:117:in `convert'
	26: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
	25: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
	24: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:215:in `convert_document'
	23: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:598:in `indent_section'
	22: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:268:in `block in convert_document'
	21: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:156:in `traverse'
	20: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:1005:in `content'
	19: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	18: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	17: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	16: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	15: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
	14: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:588:in `convert_section'
	13: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:156:in `traverse'
	12: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	11: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	10: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	 9: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	 8: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
	 7: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:588:in `convert_section'
	 6: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:156:in `traverse'
	 5: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	 4: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	 3: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	 2: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	 1: from /var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:139:in `convert'
/var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.5.4/lib/asciidoctor/pdf/converter.rb:774:in `convert_admonition': undefined method `/' for nil:NilClass (NoMethodError)
```

**Comment by pismute** [comment]
폰트 설정을 직접해야 할 것 같아요. 
해당 gem이 더 이상 관리되질 않아요(https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic).

아직 자세히 살펴보질 않아서 모르겠지만, 
- 중국어 간체(https://github.com/progit/progit2-zh)는 아직 사용중인 듯하고
- 중국어 번체(https://github.com/progit/progit2-zh-tw)랑 일본어(https://github.com/progit/progit2-ja)는 이 gem 없이 빌드하는 듯 싶네요.

물론, 넷 다 빌드 안될 가능성도 있고 시간날 때 좀 볼게요.
